# Generated by Django 4.2.6 on 2023-10-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('a', 'Confirmed'), ('b', 'Completed'), ('c', 'Canceled')], default='a', help_text='Status', max_length=1),
        ),
    ]
