# Generated by Django 4.2.6 on 2023-10-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0002_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='pictures', verbose_name='Picture'),
        ),
    ]
